plugins:
  pep8:
    enabled: true
  pylint:
    enabled: true
    channel: "beta"
    checks:
      missing-class-docstring:
        enabled: false
      missing-module-docstring:
        enabled: false
      import-error:
        enabled: false
      too-few-public-methods:
        enabled: false
      too-many-lines:
        enabled: false
      line-too-long:
        enabled: false
      invalid-name:
        enabled: false
exclude_patterns:
  - "tests/"
