version: '3'
services:
  app:
    container_name: batuta-${FLASK_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9696:5000
    volumes:
      - .:/app
    env_file:
      - .env
